routes/web.php
<?php

use App\Model\Product;
use App\Model\ProductItem;
use App\Model\ProductItemBox;
use App\Model\SaleDetail;

Route::get('/',function(){ return redirect()->route('login'); });

Route::get('/test',function(){
    $books_no = [];
    $gameCode = '90003';

    $count = 0;
    foreach(SaleDetail::where('game_code',$gameCode)->get() as $detail){
        $books_no[] = strlen($detail->code) == 20 ? substr($detail->code, 10,7) : substr($detail->code, 5, 7);
    }

    //foreach(ProductItem::where('game_code',$gameCode)->get() as $item){
    //    if($item->book_no != $books_no[$item->book_no]){
    //        echo $item->book_no;
    //    }
    //}

    ProductItem::where('game_code',$gameCode)->whereIn('book_no',$books_no)->update([
        'is_sold' => 1
    ]);

    return 'done';

    // ProductItem::where('game_code','90005')->whereIn('book_no',
    //     SaleDetail::where('game_code','90005')->pluck('book_no'))->update(['is_sale' => 1]);
});

Route::group(['namespace' => 'Admin\Auth'], function(){

    Route::get('login', ['as' => 'login', 'uses' => 'AuthController@showLoginForm']);
    Route::post('login', ['as' => 'login.post', 'uses' => 'AuthController@login']);
    Route::post('logout', ['as' => 'logout', 'uses' => 'AuthController@logout']);
});

Route::group(['middleware' => 'auth', 'namespace' => 'Admin'],function(){
    Route::get('/language/set-locale/{locale}',['uses' => 'SystemSet\Language\LanguageController@setLocale', 'as' => 'language.set-locale']);

    Route::get('/dashboard',['uses' => 'Dashboard\DashboardController@index','as' => 'dashboard']);

    Route::resource('/product/stock','Product\StockController', ['as' => 'product']);
    Route::resource('/products','Product\ProductController');

    Route::group(['namespace' => 'Stock'], function () {
        Route::resource('/stocks','StockController');
        Route::get('/box/bar-code',['uses' => 'StockController@getBoxBarCode','as' => 'box.barcode']);
        Route::get('/stocklog-detail/{refNo}',['uses' => 'StockController@getStockLogDetailByRefNo','as' => 'stocklog.detail']);
        Route::get('/stock-download-pdf',['uses' => 'StockController@generatePdf', 'as' => 'stock.pdf.download']);
        Route::get('/stock-download-excel',['uses' => 'StockController@generateExcel', 'as' => 'stock.excel.download']);
        Route::get('/get-book-list',['uses' => 'StockController@getBookList','as' => 'stocklog.get-book-list']);
    });

    Route::group(['namespace' => 'Sale'], function () {
        Route::get('/sales/get-product-by-book-code', ['uses' => 'SaleController@getProductByBookCode', 'as' => 'sale.get-product']);
        Route::get('/sales/get-products-by-box-code', ['uses' => 'SaleController@getProductByBoxCode', 'as' => 'sale.get-products']);
        Route::resource('/sales','SaleController');
        Route::get('/sale-detail/{refNo}',['uses' => 'SaleController@getSaleDetailByRefNo','as' => 'sale.detail']);
        Route::get('/sale-download-pdf',['uses' => 'SaleController@generatePdf', 'as' => 'sale.pdf.download']);
        Route::get('/sale-download-excel',['uses' => 'SaleController@generateExcel', 'as' => 'sale.excel.download']);

    });

    Route::resource('/awards','Award\AwardController');

    Route::group(['namespace' => 'Manager'],function(){
        Route::resource('/managers/roles', 'ManagerRoleController',['as' => 'managers']);
        Route::resource('/managers/password','ManagerEditPasswordController',['as' => 'managers']);
        Route::resource('/managers', 'ManagerController');
    });

    Route::group(['namespace' => 'ScanAward'], function(){
        Route::get('scan-export', ['uses' => 'ScanAwardController@exportExcel', 'as' => 'scan-export']);
        Route::get('scan-award', ['uses' => 'ScanAwardController@index', 'as' => 'scan-award']);
        Route::get('scan-summary', ['uses' => 'ScanAwardController@getScanSummary', 'as' => 'scan-summary']);

        Route::get('scan-summary/download', ['uses' => 'ScanAwardController@downloadScanSummary', 'as' => 'download-scan-summary']);
    });

    Route::group(['namespace' => 'User'],function(){

        Route::group(['middleware' => ['permission:view-user-account']], function () {
            Route::resource('/users/accounts', 'AccountController',['as' => 'users']);
        });

        Route::group(['middleware' => ['permission:view-user-account|view-user-account-log']], function () {
            Route::resource('/users/sale-network', 'SaleNetworkController',['as' => 'users']);
        });

        Route::group(['middleware' => ['permission:view-user-account-log']], function () {
            Route::resource('/users/account/logs', 'AccountLogController',['as' => 'users']);
        });

        Route::get('/user/log/download/{userId}',['uses' => 'AccountLogController@download','as' => 'user.logs.download']);
    });

    Route::group(['namespace' => 'Purchase'],function(){
        Route::get('/purchase', ['uses' => 'PurchaseController@index', 'as' => 'purchase']);
        Route::get('scan-purchase/download', ['uses' => 'PurchaseController@downloadScanPurchase', 'as' => 'download-scan-purchase']);
    });

});

Route::get('/generate-barcode',function(){
    $game_code = 'P0001';
    $batch = '19001';
    $step = 50;
    $s_book_no = 1;

    $barcodes = [];

    for($i = 1; $i<=200;$i++){
        $box = str_pad($i, 5, '0', STR_PAD_LEFT);
        $s_book = str_pad($s_book_no, 7, '0', STR_PAD_LEFT);
        $e_book = str_pad($s_book_no + $step - 1, 7, '0', STR_PAD_LEFT);
        $s_book_no = $s_book_no + $step;

        $code = $game_code.$batch.$box.$s_book.$e_book; echo "<br>";
        echo $code.'<br>';
        // $barcodes[] =
        //     [
        //         'text' => $code,
        //         'size' => 30,
        //         'orientation' => 'horizontal',
        //         'code_type' => 'code39',
        //         'print' => true,
        //         'sizefactor' => 1,
        //         'filename' => $code.'.jpeg'
        //     ];
    }

    // $bar = App::make('BarCode');
    // foreach($barcodes as $barcode) {
    //     $barcontent = $bar->barcodeFactory()->renderBarcode(
    //                                 $text=$barcode["text"],
    //                                 $size=$barcode['size'],
    //                                 $orientation=$barcode['orientation'],
    //                                 $code_type=$barcode['code_type'], // code_type : code128,code39,code128b,code128a,code25,codabar
    //                                 $print=$barcode['print'],
    //                                 $sizefactor=$barcode['sizefactor'],
    //                                 $filename = $barcode['filename']
    //                         )->filename($barcode['filename']);

    //     echo '<img alt="testing" src="'.$barcontent.'"/>';  echo "<br>";
    // }

});

//** this route run the link to transfer return bonus card */
   Route::get('/bonus-transfer', ['uses' => 'API\Balance\BalanceController@transferBonus', 'as' => 'transfer-bonus']);
//** end */

app/Http/Controllers/API/Award/AwardController.php
<?php

namespace App\Http\Controllers\API\Award;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Controllers\API\BaseController;
use App\Model\Award;
use App\User;
use App\Constants\ScratchCard;
use App\Model\UserAccountLog;
use App\Model\UserAccount;
use App\Model\ScannedAward;
use Carbon\Carbon;
use App\Model\Product;
use App\Model\ProductItem;



class AwardController extends BaseController
{
    public function verifyAward(){

        $securityCode = request()->code;

        $award = Award::whereSecurityCode(ScratchCard::encryptSecurityCode($securityCode))->first();

        if(!$award) {
            return $this->sendError(api_trans('award.invalid_code'));
        }

        $user = auth()->user();
        if($user->can_scan != 1 && !($user->username == 'Test App' || $user->username == 'cmanloksio')){
            return $this->sendError(api_trans('award.can_scan'));
        }

        $productItem = ProductItem::where('game_code', $award->game_code)
                                    ->where('batch_no', $award->batch_no)
                                    ->where('book_no', $award->book_no)
                                    ->where('is_activated', 1)
                                    ->whereNotNull('customer_id')
                                    ->when(auth()->id() != 985, function($q){
                                        $q->where('customer_id','!=',985);
                                    })
                                    ->first();

        if(!$productItem && !($user->username == 'Test App' || $user->username == 'cmanloksio')){
            // return $this->sendError(api_trans('award.card_is_activated'));
        }

        if($award->is_claimed){
            return $this->sendError(api_trans('award.is_claimed'));
        }

        $product = Product::where('game_code', $award->game_code)->first();
        $productPrice = $product->ticket_price;

        $cash_account = $user->cashAccount;
        if(!$cash_account){
            $cash_account = UserAccount::createCashAccount($user->id);
        }

        $userLog = [
            'user_id' =>  $user->id,
            'account_id' => $cash_account->id,
            'amount' => 0,
            'win_money' => 0,
            'abstract' => '',
            'log_type' => 1,
            'to_type' => 1
        ];

        $scanLog = [
            'award_level' => $award->award_level,
            'security_code' => $securityCode,
            'user_id' => $user->id,
            'award_id' => $award->id,
            'award_amount' => 0,
            'abstract' => '',
        ];

        $winMoney = 0;
        $type = '';

        $card_bonus_account = $user->cardBonusAccount;
        if(!$card_bonus_account){
            $card_bonus_account = UserAccount::createCardBonusAccount($user->id);
        }

        if($award->award_level === 15){
            $winMoney = $productPrice;

            $userLog['amount'] = $productPrice;
            $userLog['win_money'] = $winMoney + $user->win_money_card;
            $userLog['abstract'] = 'LANG_LABEL_WIN_CARD_BONUS';
            UserAccountLog::create($userLog);

            $scanLog['award_amount'] = $productPrice;
            $scanLog['abstract'] = 'Win Bonus';
            ScannedAward::create($scanLog);
        }else{
            $winMoney= $award->award_amount;

            $scanLog['award_amount'] = $winMoney;
            $scanLog['abstract'] = 'Win Money';
            ScannedAward::create($scanLog);

            $userLog['amount'] = $award->award_amount;
            $userLog['win_money'] = $winMoney + $user->win_money_card;
            $userLog['abstract'] = 'LANG_LABEL_WIN_CARD_SUM';
            UserAccountLog::create($userLog);
        }

        $award->update([
            'claimed_by' => auth()->user()->id,
            'is_claimed' => TRUE
        ]);

        $user->update([
            'win_money_card' => $winMoney + $user->win_money_card
        ]);

        $type = "Win";
        return $this->sendResponse([
            'type' => $type,
            'bonus_return' => $card_bonus_account->balance,
            'level' => $award->award_level,
            'amount' => $winMoney,
            'user_win_balance' => $user->win_money_card,
        ], api_trans('award.success').number_format($winMoney).' (R) '
           .api_trans('award.success_level'). $award->award_level
           .api_trans('award.success_transfer'));
    }

}

app/Http/Controllers/Admin/Award/AwardController.php
<?php

namespace App\Http\Controllers\Admin\Award;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Excel;
use App\Imports\AwardsImport;
use App\Model\Award;
use App\Constants\ScratchCard;

class AwardController extends Controller
{
    public function __construct(){
        $this->middleware('permission:view-award-data')->only(['index']);
        $this->middleware('permission:import-award-data')->only(['store']);
    }

    public function index()
    {
        $awards = Award::with('user')->orderBy('game_code','ASC')

                        ->when(request()->game_code, function($q){
                            $q->where('game_code',request()->game_code);
                        })
                        ->when(request()->batch_no, function($q){
                            $q->where('batch_no',request()->batch_no);
                        })
                        ->when(request()->book_no, function($q){
                            $q->where('book_no',request()->book_no);
                        })
                        ->when(request()->ticket_no, function($q){
                            $q->where('ticket_no',request()->ticket_no);
                        })
                        ->when(request()->is_claimed != '' &&  request()->is_claimed != 'any', function($q){
                            $q->where('is_claimed',request()->is_claimed);
                        })
                        ->when(request()->award_level != '' , function($q){
                            $q->where('award_level',request()->award_level);
                        })
                        ->when(request()->logistic_code != '' , function($q){
                            $q->where('logistic_code',request()->logistic_code);
                        })
                        ->when(request()->security_code != '' , function($q){
                            $q->where('security_code',ScratchCard::encryptSecurityCode(request()->security_code));
                        })

                        ->orderBy('batch_no','ASC')
                        ->orderBy('book_no','ASC')
                        ->orderBy('ticket_no','ASC')
                        ->paginate(100);

        return view('award.index',compact('awards'));
    }

    public function store(Request $request)
    {
        ini_set('memory_limit',-1);
        ini_set('max_execution_time',0);

        $file = $request->file;

        Excel::import(new AwardsImport, $file);

        return response()->json([
            'success' => true,
            'message' => 'Completed!!!',
        ]);

    }

}

resources/views/award/index.blade.php
@extends('layouts.master')

@section('content')
<!-- Page header -->
<div class="page-header page-header-light">
    <div class="page-header-content header-elements-md-inline">
        <div class="page-title d-flex py-2">
            <h4><span class="font-weight-semibold">Scratch Card Award</span></h4>
        </div>

        @can('import-award-data')
        <div class="header-elements d-none">
            <div class="d-flex justify-content-center">
                <button class="btn btn-link btn-primary btn-sm text-white" id="importExcelButton" 
                data-toggle="modal" data-target="#importModal">
                    <i class="icon-file-excel text-white mr-1"></i>Import Data 
                </button>
            </div>  
        </div>
        @endcan

    </div>

    <div class="breadcrumb-line breadcrumb-line-light header-elements-md-inline">
        <div class="d-flex">
            <div class="breadcrumb">
                <a href="{{route('dashboard')}}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> Dashboard</a>
                <span class="breadcrumb-item active">Scratch Card Data</span>
                <span class="breadcrumb-item active">Award Data</span>
            </div>
        </div>
    </div>
</div>
<!-- /page header -->

<div class="content">
    <div class="card">
        <div class="card-header">
            <div class="mb-1">
                <button class="btn btn-sm btn-primary" type="button" data-toggle="collapse" data-target="#filter" aria-expanded="false" aria-controls="collapseExample">
                    <i class="icon-filter3"> </i> Filter
                </button> 
                
                <div class="collapse mt-2" id="filter"> 
                    {{ Form::open(['route' => 'awards.index', 'method' => 'GET']) }}
                        <div class="row mb-2">
                            <div class="col-lg-2 col-md-3 col-sm-6">
                                <label for="">Game Code</label>
                                {{Form::text("game_code",request()->game_code,["class" => "form-control "])}}
                            </div>
                            <div class="col-lg-2 col-md-3 col-sm-6">
                                <label for="">Batch No</label>
                                {{Form::text("batch_no",request()->batch_no,["class" => "form-control "])}}
                            </div>
                            <div class="col-lg-2 col-md-3 col-sm-6">
                                <label for="">Book No</label>
                                {{Form::text("book_no",request()->book_no,["class" => "form-control "])}}
                            </div>
                            <div class="col-lg-2 col-md-3 col-sm-6">
                                <label for="">Ticket No</label>
                                {{Form::text("ticket_no",request()->ticket_no,["class" => "form-control "])}}
                            </div>
                            <div class="col-lg-2 col-md-3 col-sm-6">
                                <label for="">Award Level</label>
                                {{Form::number("award_level",request()->award_level,["class" => "form-control "])}}
                            </div>
                            <div class="col-lg-2 col-md-3 col-sm-6">
                                <label for="">Award Status</label>
                                <select name="is_claimed" class="form-control">
                                    <option value="any" >Any</option>
                                    <option value="0" {{ request()->is_claimed == '0' ? 'selected' : ''}}>Available</option>
                                    <option value="1" {{ request()->is_claimed == '1' ? 'selected' : ''}}>Claimed</option>
                                </select>
                            </div>
                        </div>
                        <div class="row mb-2">
                            <div class="col-lg-3 col-md-5 col-sm-6">
                                <label for="">Security Code</label>
                                {{Form::text("security_code",request()->security_code,["class" => "form-control "])}}
                            </div>
                            <div class="col-lg-3 col-md-5 col-sm-6">
                                <label for="">Logistic Code</label>
                                {{Form::text("logistic_code",request()->logistic_code,["class" => "form-control "])}}
                            </div>
                        </div>
                        <button type="submit" class="btn btn-sm btn-success">Search</button>
                        <a href="{{route('awards.index')}}" class="btn btn-sm btn-danger">Reset</a>
                    {{ Form::close() }}
                </div>
            </div>
            <div class="table-responsive">
                <table class="table table-bordered">
                    <thead>
                        <tr class="bg-slate-800">
                            <th>#</th>
                            <th>Game Code</th>
                            <th>Batch Number</th>
                            <th>Book Number</th>
                            <th>Ticket Number</th>
                            {{-- <th>Award Level</th>
                            <th>Award Amount</th> --}}
                            <th>Status</th>
                            <th>Claimed By</th>
                            <th>Scanned At</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if(isset($awards) && $awards->count() > 0)
                            @foreach($awards as $key => $row)
                            <tr class="{{ $row->is_claimed ? 'table-danger' : ''}}">
                                <td>{{($awards->perPage() * ($awards->currentPage() - 1)) + $key + 1}}</td>
                                <td>{{ $row->game_code }}</td>
                                <td>{{ $row->batch_no }}</td>
                                <td>{{ $row->book_no }}</td>
                                <td>{{ $row->ticket_no }}</td>
                                {{-- <td>{{ $row->award_level }}</td>
                                <td>{{ $row->award_amount }}</td> --}}
                                <td>
                                    @if($row->is_claimed == 1)
                                        <span class="badge badge-danger">Claimed</span>
                                    @else 
                                        <span class="badge badge-success">Available</span>
                                    @endif
                                </td>
                                <td>{{ $row->user ? $row->user->username : 'N/A' }}</td>
                                <td>{{ $row->scanned_at }}</td>
                            </tr>
                            @endforeach
                        @else 
                            <tr>
                                <td colspan="9"> No data</td>
                            </tr>
                        @endif
                    </tbody>
                </table>
            </div>
            @if(isset($awards) && count($awards) > 0)
            <div class="card-footer">
                @if($awards->hasPages())
                    <div class="mb-2">
                        {!! $awards->appends(Input::except('page'))->render() !!}
                    </div>
                @endif
                <div>
                    Showing {{$awards->firstItem()}} to {{$awards->lastItem()}}
                    of  {{$awards->total()}} entries
                </div>
            </div>
            @endif
        </div>
    </div>
</div>
<div id="importModal" class="modal fade" tabindex="-1" >
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header bg-teal-400">
                <h5 class="modal-title">Import Award Data</h5>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body" id="importModalBody">
                <p>Upload excel file with extension (.xlsx) below and click Import button.</p>
                <form id="importUploadForm" method="POST" enctype='multipart/form-data'>
                    <div class="form-group row">
                        <div class="col-lg-12">
                            <input type="file" name="file" class="form-control-uniform" data-fouc>
                        </div>
                    </div>
                </form>
                <span class="text-danger error-message"></span>
            </div>
            <div class="modal-footer">
                <button type="button" id="importBtn" data-route="{{ route('awards.store') }}" class="btn btn-success float-right one-click-btn">Start Import</button>
            </div>
        </div>
    </div>
</div>
@endsection

@section('page-script')
<script src="/global_assets/js/demo_pages/form_inputs.js"></script>
<script src="/global_assets/js/plugins/forms/styling/uniform.min.js"></script>
@endsection