routes/web.php
<?php

use App\Model\Product;
use App\Model\ProductItem;
use App\Model\ProductItemBox;
use App\Model\SaleDetail;

Route::get('/',function(){ return redirect()->route('login'); });

Route::get('/test',function(){
    $books_no = [];
    $gameCode = '90003';

    $count = 0;
    foreach(SaleDetail::where('game_code',$gameCode)->get() as $detail){
        $books_no[] = strlen($detail->code) == 20 ? substr($detail->code, 10,7) : substr($detail->code, 5, 7);
    }

    //foreach(ProductItem::where('game_code',$gameCode)->get() as $item){
    //    if($item->book_no != $books_no[$item->book_no]){
    //        echo $item->book_no;
    //    }
    //}

    ProductItem::where('game_code',$gameCode)->whereIn('book_no',$books_no)->update([
        'is_sold' => 1
    ]);

    return 'done';

    // ProductItem::where('game_code','90005')->whereIn('book_no',
    //     SaleDetail::where('game_code','90005')->pluck('book_no'))->update(['is_sale' => 1]);
});

Route::group(['namespace' => 'Admin\Auth'], function(){

    Route::get('login', ['as' => 'login', 'uses' => 'AuthController@showLoginForm']);
    Route::post('login', ['as' => 'login.post', 'uses' => 'AuthController@login']);
    Route::post('logout', ['as' => 'logout', 'uses' => 'AuthController@logout']);
});

Route::group(['middleware' => 'auth', 'namespace' => 'Admin'],function(){
    Route::get('/language/set-locale/{locale}',['uses' => 'SystemSet\Language\LanguageController@setLocale', 'as' => 'language.set-locale']);

    Route::get('/dashboard',['uses' => 'Dashboard\DashboardController@index','as' => 'dashboard']);

    Route::resource('/product/stock','Product\StockController', ['as' => 'product']);
    Route::resource('/products','Product\ProductController');

    Route::group(['namespace' => 'Stock'], function () {
        Route::resource('/stocks','StockController');
        Route::get('/box/bar-code',['uses' => 'StockController@getBoxBarCode','as' => 'box.barcode']);
        Route::get('/stocklog-detail/{refNo}',['uses' => 'StockController@getStockLogDetailByRefNo','as' => 'stocklog.detail']);
        Route::get('/stock-download-pdf',['uses' => 'StockController@generatePdf', 'as' => 'stock.pdf.download']);
        Route::get('/stock-download-excel',['uses' => 'StockController@generateExcel', 'as' => 'stock.excel.download']);
        Route::get('/get-book-list',['uses' => 'StockController@getBookList','as' => 'stocklog.get-book-list']);
    });

    Route::group(['namespace' => 'Sale'], function () {
        Route::get('/sales/get-product-by-book-code', ['uses' => 'SaleController@getProductByBookCode', 'as' => 'sale.get-product']);
        Route::get('/sales/get-products-by-box-code', ['uses' => 'SaleController@getProductByBoxCode', 'as' => 'sale.get-products']);
        Route::resource('/sales','SaleController');
        Route::get('/sale-detail/{refNo}',['uses' => 'SaleController@getSaleDetailByRefNo','as' => 'sale.detail']);
        Route::get('/sale-download-pdf',['uses' => 'SaleController@generatePdf', 'as' => 'sale.pdf.download']);
        Route::get('/sale-download-excel',['uses' => 'SaleController@generateExcel', 'as' => 'sale.excel.download']);

    });

    Route::resource('/awards','Award\AwardController');

    Route::group(['namespace' => 'Manager'],function(){
        Route::resource('/managers/roles', 'ManagerRoleController',['as' => 'managers']);
        Route::resource('/managers/password','ManagerEditPasswordController',['as' => 'managers']);
        Route::resource('/managers', 'ManagerController');
    });

    Route::group(['namespace' => 'ScanAward'], function(){
        Route::get('scan-export', ['uses' => 'ScanAwardController@exportExcel', 'as' => 'scan-export']);
        Route::get('scan-award', ['uses' => 'ScanAwardController@index', 'as' => 'scan-award']);
        Route::get('scan-summary', ['uses' => 'ScanAwardController@getScanSummary', 'as' => 'scan-summary']);

        Route::get('scan-summary/download', ['uses' => 'ScanAwardController@downloadScanSummary', 'as' => 'download-scan-summary']);
    });

    Route::group(['namespace' => 'User'],function(){

        Route::group(['middleware' => ['permission:view-user-account']], function () {
            Route::resource('/users/accounts', 'AccountController',['as' => 'users']);
        });

        Route::group(['middleware' => ['permission:view-user-account|view-user-account-log']], function () {
            Route::resource('/users/sale-network', 'SaleNetworkController',['as' => 'users']);
        });

        Route::group(['middleware' => ['permission:view-user-account-log']], function () {
            Route::resource('/users/account/logs', 'AccountLogController',['as' => 'users']);
        });

        Route::get('/user/log/download/{userId}',['uses' => 'AccountLogController@download','as' => 'user.logs.download']);
    });

    Route::group(['namespace' => 'Purchase'],function(){
        Route::get('/purchase', ['uses' => 'PurchaseController@index', 'as' => 'purchase']);
        Route::get('scan-purchase/download', ['uses' => 'PurchaseController@downloadScanPurchase', 'as' => 'download-scan-purchase']);
    });

});

Route::get('/generate-barcode',function(){
    $game_code = 'P0001';
    $batch = '19001';
    $step = 50;
    $s_book_no = 1;

    $barcodes = [];

    for($i = 1; $i<=200;$i++){
        $box = str_pad($i, 5, '0', STR_PAD_LEFT);
        $s_book = str_pad($s_book_no, 7, '0', STR_PAD_LEFT);
        $e_book = str_pad($s_book_no + $step - 1, 7, '0', STR_PAD_LEFT);
        $s_book_no = $s_book_no + $step;

        $code = $game_code.$batch.$box.$s_book.$e_book; echo "<br>";
        echo $code.'<br>';
        // $barcodes[] =
        //     [
        //         'text' => $code,
        //         'size' => 30,
        //         'orientation' => 'horizontal',
        //         'code_type' => 'code39',
        //         'print' => true,
        //         'sizefactor' => 1,
        //         'filename' => $code.'.jpeg'
        //     ];
    }

    // $bar = App::make('BarCode');
    // foreach($barcodes as $barcode) {
    //     $barcontent = $bar->barcodeFactory()->renderBarcode(
    //                                 $text=$barcode["text"],
    //                                 $size=$barcode['size'],
    //                                 $orientation=$barcode['orientation'],
    //                                 $code_type=$barcode['code_type'], // code_type : code128,code39,code128b,code128a,code25,codabar
    //                                 $print=$barcode['print'],
    //                                 $sizefactor=$barcode['sizefactor'],
    //                                 $filename = $barcode['filename']
    //                         )->filename($barcode['filename']);

    //     echo '<img alt="testing" src="'.$barcontent.'"/>';  echo "<br>";
    // }

});

//** this route run the link to transfer return bonus card */
   Route::get('/bonus-transfer', ['uses' => 'API\Balance\BalanceController@transferBonus', 'as' => 'transfer-bonus']);
//** end */

app/Http/Controllers/Admin/ScanAward/ScanAwardController.php
<?php

namespace App\Http\Controllers\Admin\ScanAward;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Model\ScannedAward;
use App\User;
use App\Exports\ScanAwardExport;
use App\Exports\ScanSummaryExport;
use Maatwebsite\Excel\Facades\Excel;
use DB;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;

class ScanAwardController extends Controller
{
    public function index(){
       $awardScans = ScannedAward::orderBy('created_at', 'DESC')
                                ->when(request()->award_level, function($q){
                                        $q->where('award_level', request()->award_level);
                                    })
                                ->when(request()->customer_id, function($q){
                                        $q->where('user_id', request()->customer_id);
                                    })
                                ->when(request()->award_label, function($q){
                                        $q->where('abstract', request()->award_label);
                                    })
                                ->when(request()->ticket_number, function($q){
                                        $q->where('security_code', 'like', request()->ticket_number.'%');
                                    })
                                ->when(request()->started_date && request()->ended_date, function($q){
                                        $q->whereBetween('created_at',[request()->started_date,request()->ended_date]);
                                })->paginate(25);

        $customers = getCustomers();

       return view('scan-award.index', compact('awardScans', 'customers'));
    }

    public function exportExcel(){

        $fileName = '';

        if(request()->award_level){
            $fileName = 'ScanLog-Report ('.request()->award_level.').xlsx';
        }elseif(request()->award_label){
            $fileName = 'ScanLog-Report ('.request()->award_label.').xlsx';
        }elseif(request()->ticket_number){
            $fileName = 'ScanLog-Report ('.request()->ticket_number.').xlsx';
        }
        elseif(request()->started_date && request()->ended_date){
            $fileName = 'ScanLog-Report ('.request()->started_date.' – '.request()->ended_date.').xlsx';
        }else{
            $fileName = 'ScanLog-Report.xlsx';
        }

        return Excel::download(new ScanAwardExport, $fileName);
    }

    public function getScanSummary(){

        $awardScans = ScannedAward::with('customer')

                                ->when(request()->award_level, function($q){
                                        $q->where('award_level', request()->award_level);
                                    })
                                ->when(request()->customer_id, function($q){
                                        $q->where('user_id', request()->customer_id);
                                    })
                                ->when(request()->award_label, function($q){
                                        $q->where('abstract', request()->award_label);
                                    })
                                ->when(request()->ticket_number, function($q){
                                        $q->where('security_code', 'like', request()->ticket_number.'%');
                                    })
                                ->when(request()->started_date && request()->ended_date, function($q){
                                        $q->whereBetween('created_at',[request()->started_date,request()->ended_date]);
                                })
                                ->select(
                                    'user_id',
                                    DB::raw('count(id) as total_ticket'),
                                    DB::raw('sum(award_amount) as total_amount')
                                )
                                ->groupBy('user_id')
                                ->paginate(25);

        $customers = getCustomers();

        return view('scan-award.scan-summary', compact('awardScans', 'customers'));
    }

    public function downloadScanSummary(){

     return Excel::download(new ScanSummaryExport, 'summary.xlsx');

    }
}

resources/views/scan-award/index.blade.php
@extends('layouts.master')
<style>
    table { page-break-inside:auto }
    tr    { page-break-inside:avoid; page-break-after:auto }
    thead { display:table-header-group }
    tfoot { display:table-footer-group }
    #address{
                width:300px;

        }
    #address ul {

        margin: 0px;
        padding: 0px;
        overflow-wrap: break-word;
        text-decoration: none;
    }
</style>

@section('content')
<!-- Page header -->
<div class="page-header page-header-light">
    <div class="page-header-content header-elements-md-inline">
        <div class="page-title d-flex py-2">
            <h4><span class="font-weight-semibold">Awards Scanned</span></h4>
        </div>

        <div class="header-elements d-none">
            <div class="d-flex justify-content-center">
                {{-- @canany(['export-sale']) --}}
                    <a href="" target="_BLANK" data-route="{{ route('scan-export') }}" class="btn bg-teal-400 btn-sm download-excel mr-2">
                        <i class="icon-download mr-1 text-white"></i> Download Excel
                    </a>
                {{-- @endcanany --}}

                {{-- @canany(['add-new-sale'])
                <a href="{{ route('sales.create') }}" class="btn btn-primary btn-sm">
                    <i class="icon-file-plus2 text-white"></i> Add New Sale
                </a>
                @endcanany --}}
            </div>
        </div>

    </div>

    <div class="breadcrumb-line breadcrumb-line-light header-elements-md-inline">
        <div class="d-flex">
            <div class="breadcrumb">
                <a href="{{route('dashboard')}}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> Dashboard</a>
                <span class="breadcrumb-item active">Awards-Scanned</span>
            </div>
        </div>
    </div>
</div>
<!-- /page header -->

<div class="content">
    <div class="card">
        <div class="card-header">
            @include('includes.success-msg')
            @include('includes.error-msg')
            <div class="mb-1">
                <button class="btn btn-sm btn-primary" type="button" data-toggle="collapse" data-target="#filter" aria-expanded="false" aria-controls="collapseExample">
                    <i class="icon-filter3"> </i> Filter
                </button>

                <div class="collapse mt-2" id="filter">
                    {{ Form::open(['route' => 'scan-award', 'method' => 'GET']) }}
                        <div class="row mb-2">
                            <div class="col-lg-3 col-md-3 col-sm-6">
                                <label for="">Award Level</label>
                                {{Form::number("award_level", request()->award_level, ["class" => "form-control ", "placeholder" => "Enter Award-Level"])}}
                            </div>

                            <div class="col-lg-3 col-md-3 col-sm-6">
                                <label for="">Ticket Number</label>
                                {{Form::text("ticket_number", request()->ticket_number, ["class" => "form-control ", "placeholder" => "Enter Ticket-Number"])}}
                            </div>

                            <div class="col-lg-3 col-md-3 col-sm-6">
                                <label for="">Award Lable</label>
                                {{ Form::select("award_label", ['Return Bonus' => 'Return Bonus', 'Win Money' => 'Win Money', 'Win Bonus' => 'Win Bonus'], request()->award_label, ["class" => "form-control", "placeholder" => "Select Label Award", "id" => "label"]) }}
                            </div>
                            
                            <div class="col-lg-3 col-md-3 col-sm-6">
                                <label for="">Customer Name</label>
                                {{ Form::select("customer_id", $customers, request()->customer_id,["class" => "form-control", "placeholder" => "Select Customer Name", "id" => "customer"]) }}
                            </div>

                            <div class="col-lg-3 col-md-4 col-sm-6">
                                <div class="form-group mb-0">
                                    <label class="form-group-float-label font-weight-semibold is-visible">Start Date</label>
                                    <div class="input-group">
                                        <span class="input-group-prepend">
                                            <span class="input-group-text"><i class="icon-calendar3"></i></span>
                                        </span>
                                        {{Form::text("started_date",isset($_GET['started_date']) ? $_GET['started_date'] : date('Y-m-d 00:00:00',strtotime('first day of this month')),
                                            ["class" => "form-control datetimepicker"])
                                        }}
                                    </div>
                                </div>
                            </div>

                            <div class="col-lg-3 col-md-4 col-sm-6">
                                <div class="form-group mb-0">
                                    <label class="form-group-float-label font-weight-semibold is-visible">Ended Date</label>
                                    <div class="input-group">
                                        <span class="input-group-prepend">
                                            <span class="input-group-text"><i class="icon-calendar3"></i></span>
                                        </span>
                                        {{Form::text("ended_date",isset($_GET['ended_date']) ? $_GET['ended_date'] : date('Y-m-d 23:59:59',strtotime('last day of this month')),
                                            ["class" => "form-control datetimepicker"])
                                        }}
                                    </div>
                                </div>
                            </div>
                        </div>

                        <button type="submit" class="btn btn-sm btn-success">Search</button>
                        <a href="{{route('scan-award')}}" class="btn btn-sm btn-danger">Reset</a>
                    {{ Form::close() }}
                </div>
            </div>
            <div class="table-responsive">
                <table class="table table-bordered">
                    <thead>
                        <tr class="bg-slate-800">
                            <th>#</th>
                            <th>Award Amount</th>
                            <th>Award Level</th>
                            <th>Ticket Number</th>
                            <th>Award Label</th>
                            <th>Scanned At</th>
                            <th>Scanned By</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if(isset($awardScans) && $awardScans->count() > 0)
                            @foreach($awardScans as $key => $row)
                            <tr>
                                <td>{{($awardScans->perPage() * ($awardScans->currentPage() - 1)) + $key + 1}}</td>
                                <td>(R) {{ $row->award_amount }}</td>
                                <td>{{ $row->award_level}}</td>
                                <td>{{ substr($row->security_code,0,20) }}</td>
                                <td>{{ $row->abstract}}</td>
                                <td>{{ $row->created_at }}</td>
                                <td>{{ $row->customer ? $row->customer->username : ''}}</td>
                            </tr>
                            @endforeach
                        @else
                            <tr>
                                <td colspan="9"> No data</td>
                            </tr>
                        @endif
                    </tbody>
                </table>
            </div>
            @if(isset($awardScans) && count($awardScans) > 0)
            <div class="card-footer">
                @if($awardScans->hasPages())
                    <div class="mb-2">
                        {!! $awardScans->appends(Input::except('page'))->render() !!}
                    </div>
                @endif
                <div>
                    Showing {{$awardScans->firstItem()}} to {{$awardScans->lastItem()}}
                    of  {{$awardScans->total()}} entries
                </div>
            </div>
            @endif
        </div>
    </div>
</div>

@endsection

@section('page-script')
<script src="/global_assets/js/demo_pages/form_inputs.js"></script>
<script src="/global_assets/js/plugins/forms/styling/uniform.min.js"></script>
<script src="/global_assets/js/plugins/ui/moment/moment.min.js"></script>
<script src="/global_assets/js/plugins/pickers/daterangepicker.js"></script>

<script>
    if($('.download-excel').length > 0){
        $('.download-excel').attr('href',$('.download-excel').data('route') + location.search)
    }
</script>

@endsection

resources/views/scan-award/scan-summary.blade.php
@extends('layouts.master')
<style>
    table { page-break-inside:auto }
    tr    { page-break-inside:avoid; page-break-after:auto }
    thead { display:table-header-group }
    tfoot { display:table-footer-group }
    #address{
                width:300px;

        }
    #address ul {

        margin: 0px;
        padding: 0px;
        overflow-wrap: break-word;
        text-decoration: none;
    }
</style>

@section('content')
<!-- Page header -->
<div class="page-header page-header-light">
    <div class="page-header-content header-elements-md-inline">
        <div class="page-title d-flex py-2">
            <h4><span class="font-weight-semibold">Awards Scanned Summary</span></h4>
        </div>

        <div class="header-elements d-none">
            <div class="d-flex justify-content-center">
                @if(request()->award_label === 'Return Bonus' && auth()->id() == 44)
                <a href="{{ route('transfer-bonus') }}" class="btn btn-primary btn-sm">
                    <i class="icon-file-plus2 text-white"></i> Transfer Bonus
                </a>
                @endif
                <a href="" data-route="{{ route('download-scan-summary') }}" target="_BLANK" class="btn bg-teal-400 download-excel btn-sm mr-2">
                    <i class="icon-download mr-1 text-white"></i> Download Excel
                </a>
            </div>
        </div>

    </div>

    <div class="breadcrumb-line breadcrumb-line-light header-elements-md-inline">
        <div class="d-flex">
            <div class="breadcrumb">
                <a href="{{route('dashboard')}}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> Dashboard</a>
                <span class="breadcrumb-item active">Awards-Scanned-Summary</span>
            </div>
        </div>
    </div>
</div>
<!-- /page header -->

<div class="content">
    <div class="card">
        <div class="card-header">
            @include('includes.success-msg')
            @include('includes.error-msg')
            <div class="mb-1">
                <button class="btn btn-sm btn-primary" type="button" data-toggle="collapse" data-target="#filter" aria-expanded="false" aria-controls="collapseExample">
                    <i class="icon-filter3"> </i> Filter
                </button>

                <div class="collapse mt-2" id="filter">
                    {{ Form::open(['route' => 'scan-summary', 'method' => 'GET']) }}
                        <div class="row mb-2">
                            {{-- <div class="col-lg-3 col-md-3 col-sm-6">
                                <label for="">Award Level</label>
                                {{Form::number("award_level", request()->award_level, ["class" => "form-control ", "placeholder" => "Enter Award-Level"])}}
                            </div> --}}

                            {{-- <div class="col-lg-3 col-md-3 col-sm-6">
                                <label for="">Ticket Number</label>
                                {{Form::text("ticket_number", request()->ticket_number, ["class" => "form-control ", "placeholder" => "Enter Ticket-Number"])}}
                            </div> --}}

                            <div class="col-lg-3 col-md-3 col-sm-6">
                                <label for="">Award Lable</label>
                                {{ Form::select("award_label", ['Return Bonus' => 'Return Bonus', 'Win Money' => 'Win Money', 'Win Bonus' => 'Win Bonus'], request()->award_label, ["class" => "form-control", "placeholder" => "Select Label Award", "id" => "label"]) }}
                            </div>

                            <div class="col-lg-3 col-md-3 col-sm-6">
                                <label for="">Customer Name</label>
                                {{ Form::select("customer_id", $customers, request()->customer_id,["class" => "form-control", "placeholder" => "Select Customer Name", "id" => "customer"]) }}
                            </div>

                            <div class="col-lg-3 col-md-4 col-sm-6">
                                <div class="form-group mb-0">
                                    <label class="form-group-float-label font-weight-semibold is-visible">Start Date</label>
                                    <div class="input-group">
                                        <span class="input-group-prepend">
                                            <span class="input-group-text"><i class="icon-calendar3"></i></span>
                                        </span>
                                        {{Form::text("started_date",isset($_GET['started_date']) ? $_GET['started_date'] : date('Y-m-d 00:00:00',strtotime('first day of this month')),
                                            ["class" => "form-control datetimepicker"])
                                        }}
                                    </div>
                                </div>
                            </div>

                            <div class="col-lg-3 col-md-4 col-sm-6">
                                <div class="form-group mb-0">
                                    <label class="form-group-float-label font-weight-semibold is-visible">Ended Date</label>
                                    <div class="input-group">
                                        <span class="input-group-prepend">
                                            <span class="input-group-text"><i class="icon-calendar3"></i></span>
                                        </span>
                                        {{Form::text("ended_date",isset($_GET['ended_date']) ? $_GET['ended_date'] : date('Y-m-d 23:59:59',strtotime('last day of this month')),
                                            ["class" => "form-control datetimepicker"])
                                        }}
                                    </div>
                                </div>
                            </div>
                        </div>

                        <button type="submit" class="btn btn-sm btn-success">Search</button>
                        <a href="{{route('scan-summary')}}" class="btn btn-sm btn-danger">Reset</a>
                    {{ Form::close() }}
                </div>
            </div>
            <div class="table-responsive">
                <table class="table table-bordered">
                    <thead>
                        <tr class="bg-slate-800">
                            <th>#</th>
                            <th>Scanned By</th>
                            <th>Total Amount</th>
                            <th>Total Tickets</th>
                            {{-- <th>Total Win</th>
                            <th>Total Bonus</th>
                            <th>Total Return</th> --}}
                        </tr>
                    </thead>
                    <tbody>
                        @if(isset($awardScans) && $awardScans->count() > 0)
                            @foreach($awardScans as $key => $row)
                            <tr>
                                <td>{{($awardScans->perPage() * ($awardScans->currentPage() - 1)) + $key + 1}}</td>
                                <td>{{ $row->customer ? $row->customer->username : ''}}</td>
                                <td>(R) {{ $row->total_amount }}</td>
                                <td>{{ $row->total_ticket}}</td>
                                {{-- <td></td>
                                <td></td>
                                <td></td> --}}
                            </tr>
                            @endforeach
                        @else
                            <tr>
                                <td colspan="9"> No data</td>
                            </tr>
                        @endif
                    </tbody>
                </table>
            </div>
            @if(isset($awardScans) && count($awardScans) > 0)
            <div class="card-footer">
                @if($awardScans->hasPages())
                    <div class="mb-2">
                        {!! $awardScans->appends(Input::except('page'))->render() !!}
                    </div>
                @endif
                <div>
                    Showing {{$awardScans->firstItem()}} to {{$awardScans->lastItem()}}
                    of  {{$awardScans->total()}} entries
                </div>
            </div>
            @endif
        </div>
    </div>
</div>

@endsection

@section('page-script')
<script src="/global_assets/js/demo_pages/form_inputs.js"></script>
<script src="/global_assets/js/plugins/forms/styling/uniform.min.js"></script>
<script src="/global_assets/js/plugins/ui/moment/moment.min.js"></script>
<script src="/global_assets/js/plugins/pickers/daterangepicker.js"></script>

<script>
    if($('.download-excel').length > 0){
        $('.download-excel').attr('href',$('.download-excel').data('route') + location.search)
    }
</script>

@endsection