routes/web.php
<?php

use App\Model\Product;
use App\Model\ProductItem;
use App\Model\ProductItemBox;
use App\Model\SaleDetail;

Route::get('/',function(){ return redirect()->route('login'); });

Route::get('/test',function(){
    $books_no = [];
    $gameCode = '90003';

    $count = 0;
    foreach(SaleDetail::where('game_code',$gameCode)->get() as $detail){
        $books_no[] = strlen($detail->code) == 20 ? substr($detail->code, 10,7) : substr($detail->code, 5, 7);
    }

    //foreach(ProductItem::where('game_code',$gameCode)->get() as $item){
    //    if($item->book_no != $books_no[$item->book_no]){
    //        echo $item->book_no;
    //    }
    //}

    ProductItem::where('game_code',$gameCode)->whereIn('book_no',$books_no)->update([
        'is_sold' => 1
    ]);

    return 'done';

    // ProductItem::where('game_code','90005')->whereIn('book_no',
    //     SaleDetail::where('game_code','90005')->pluck('book_no'))->update(['is_sale' => 1]);
});

Route::group(['namespace' => 'Admin\Auth'], function(){

    Route::get('login', ['as' => 'login', 'uses' => 'AuthController@showLoginForm']);
    Route::post('login', ['as' => 'login.post', 'uses' => 'AuthController@login']);
    Route::post('logout', ['as' => 'logout', 'uses' => 'AuthController@logout']);
});

Route::group(['middleware' => 'auth', 'namespace' => 'Admin'],function(){
    Route::get('/language/set-locale/{locale}',['uses' => 'SystemSet\Language\LanguageController@setLocale', 'as' => 'language.set-locale']);

    Route::get('/dashboard',['uses' => 'Dashboard\DashboardController@index','as' => 'dashboard']);

    Route::resource('/product/stock','Product\StockController', ['as' => 'product']);
    Route::resource('/products','Product\ProductController');

    Route::group(['namespace' => 'Stock'], function () {
        Route::resource('/stocks','StockController');
        Route::get('/box/bar-code',['uses' => 'StockController@getBoxBarCode','as' => 'box.barcode']);
        Route::get('/stocklog-detail/{refNo}',['uses' => 'StockController@getStockLogDetailByRefNo','as' => 'stocklog.detail']);
        Route::get('/stock-download-pdf',['uses' => 'StockController@generatePdf', 'as' => 'stock.pdf.download']);
        Route::get('/stock-download-excel',['uses' => 'StockController@generateExcel', 'as' => 'stock.excel.download']);
        Route::get('/get-book-list',['uses' => 'StockController@getBookList','as' => 'stocklog.get-book-list']);
    });

    Route::group(['namespace' => 'Sale'], function () {
        Route::get('/sales/get-product-by-book-code', ['uses' => 'SaleController@getProductByBookCode', 'as' => 'sale.get-product']);
        Route::get('/sales/get-products-by-box-code', ['uses' => 'SaleController@getProductByBoxCode', 'as' => 'sale.get-products']);
        Route::resource('/sales','SaleController');
        Route::get('/sale-detail/{refNo}',['uses' => 'SaleController@getSaleDetailByRefNo','as' => 'sale.detail']);
        Route::get('/sale-download-pdf',['uses' => 'SaleController@generatePdf', 'as' => 'sale.pdf.download']);
        Route::get('/sale-download-excel',['uses' => 'SaleController@generateExcel', 'as' => 'sale.excel.download']);

    });

    Route::resource('/awards','Award\AwardController');

    Route::group(['namespace' => 'Manager'],function(){
        Route::resource('/managers/roles', 'ManagerRoleController',['as' => 'managers']);
        Route::resource('/managers/password','ManagerEditPasswordController',['as' => 'managers']);
        Route::resource('/managers', 'ManagerController');
    });

    Route::group(['namespace' => 'ScanAward'], function(){
        Route::get('scan-export', ['uses' => 'ScanAwardController@exportExcel', 'as' => 'scan-export']);
        Route::get('scan-award', ['uses' => 'ScanAwardController@index', 'as' => 'scan-award']);
        Route::get('scan-summary', ['uses' => 'ScanAwardController@getScanSummary', 'as' => 'scan-summary']);

        Route::get('scan-summary/download', ['uses' => 'ScanAwardController@downloadScanSummary', 'as' => 'download-scan-summary']);
    });

    Route::group(['namespace' => 'User'],function(){

        Route::group(['middleware' => ['permission:view-user-account']], function () {
            Route::resource('/users/accounts', 'AccountController',['as' => 'users']);
        });

        Route::group(['middleware' => ['permission:view-user-account|view-user-account-log']], function () {
            Route::resource('/users/sale-network', 'SaleNetworkController',['as' => 'users']);
        });

        Route::group(['middleware' => ['permission:view-user-account-log']], function () {
            Route::resource('/users/account/logs', 'AccountLogController',['as' => 'users']);
        });

        Route::get('/user/log/download/{userId}',['uses' => 'AccountLogController@download','as' => 'user.logs.download']);
    });

    Route::group(['namespace' => 'Purchase'],function(){
        Route::get('/purchase', ['uses' => 'PurchaseController@index', 'as' => 'purchase']);
        Route::get('scan-purchase/download', ['uses' => 'PurchaseController@downloadScanPurchase', 'as' => 'download-scan-purchase']);
    });

});

Route::get('/generate-barcode',function(){
    $game_code = 'P0001';
    $batch = '19001';
    $step = 50;
    $s_book_no = 1;

    $barcodes = [];

    for($i = 1; $i<=200;$i++){
        $box = str_pad($i, 5, '0', STR_PAD_LEFT);
        $s_book = str_pad($s_book_no, 7, '0', STR_PAD_LEFT);
        $e_book = str_pad($s_book_no + $step - 1, 7, '0', STR_PAD_LEFT);
        $s_book_no = $s_book_no + $step;

        $code = $game_code.$batch.$box.$s_book.$e_book; echo "<br>";
        echo $code.'<br>';
        // $barcodes[] =
        //     [
        //         'text' => $code,
        //         'size' => 30,
        //         'orientation' => 'horizontal',
        //         'code_type' => 'code39',
        //         'print' => true,
        //         'sizefactor' => 1,
        //         'filename' => $code.'.jpeg'
        //     ];
    }

    // $bar = App::make('BarCode');
    // foreach($barcodes as $barcode) {
    //     $barcontent = $bar->barcodeFactory()->renderBarcode(
    //                                 $text=$barcode["text"],
    //                                 $size=$barcode['size'],
    //                                 $orientation=$barcode['orientation'],
    //                                 $code_type=$barcode['code_type'], // code_type : code128,code39,code128b,code128a,code25,codabar
    //                                 $print=$barcode['print'],
    //                                 $sizefactor=$barcode['sizefactor'],
    //                                 $filename = $barcode['filename']
    //                         )->filename($barcode['filename']);

    //     echo '<img alt="testing" src="'.$barcontent.'"/>';  echo "<br>";
    // }

});

//** this route run the link to transfer return bonus card */
   Route::get('/bonus-transfer', ['uses' => 'API\Balance\BalanceController@transferBonus', 'as' => 'transfer-bonus']);
//** end */

app/Http/Controllers/Admin/Product/ProductController.php
<?php

namespace App\Http\Controllers\Admin\Product;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Model\Product;
use App\Model\ProductUnit;
use DB;

class ProductController extends Controller
{
    public function __construct(){
        $this->middleware('permission:view-product')->only(['index']);
        $this->middleware('permission:product-modification')->only(['update','delete']);
        $this->middleware('permission:add-new-product')->only(['create','store']);
    }

    public function index()
    {
        $products = Product::with('product_unit','available_product_items')
                ->when(request()->game_code, function($q){
                    $q->where('game_code',request()->game_code);
                })
                ->when(request()->name, function($q){
                    $q->where('name',request()->name);
                })
                ->orderBy('game_code','ASC')
                ->paginate(20);

        return view('product.index',compact('products'));
    }

    public function create()
    {
        $units = ProductUnit::orderBy('name','ASC')->pluck('name','id')->toArray();

        return view('product.add-update',compact('units'));
    }

    public function store(Request $request)
    {
        $this->validate($request,[
            'game_code' => 'required|max:5|min:5|unique:products,game_code',
            'name' => 'required|unique:products,name',
            'ticket_price' => 'required|numeric',
            'ticket_qty' => 'required|numeric'
        ]);

        $this->saveDB($request->all());

        return redirect()->route('products.index')->withSuccess('You have just added a Product successfully!');
    }


    public function show($id)
    {
        //
    }


    public function edit($id)
    {
        $units = ProductUnit::orderBy('name','ASC')->pluck('name','id')->toArray();
        $product = Product::find($id);

        return view('product.add-update',compact('product','units'));
    }


    public function update(Request $request, $id)
    {
        $this->validate($request,[
            'game_code' => 'required|max:5|min:5|unique:products,game_code,'.$id,
            'name' => 'required|unique:products,name,'.$id
        ]);

        $this->saveDB($request->all(),$id);

        return redirect()->route('products.index')->withSuccess('You have just update a Product successfully!');
    }


    public function destroy($id)
    {
        $product = Product::find($id);

        DB::beginTransaction();
        if($product){
            try{
                $product->delete();
                $result = "true";
                DB::commit();
            }catch(Exception $ex){
                $result = "false";
                DB::rollback();
            }

        }
        return response()->json(['success' => $result]);
    }

    public function saveDB($data,$id = null){

        DB::beginTransaction();
        try{

            if($id > 0 && $id != null){
                $product = Product::find($id);
                $data['updated_by'] = auth()->user()->id;

            }else{
                $product = new Product();
                $data['created_by'] = auth()->user()->id;
                $data['updated_by'] = auth()->user()->id;
            }

            $product->fill($data);
            $product->save($data);
            DB::commit();
        }catch(Exception $ex){
            DB::rollback();
        }
    }
}

app/Http/Controllers/Admin/Product/StockController.php
<?php

namespace App\Http\Controllers\Admin\Product;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Model\ProductItem;
use App\Model\Product;

class StockController extends Controller
{
    public function index()
    {
        $productItems = ProductItem::with('product','product.product_unit')
                                    ->orderBy('game_code','ASC')
                                    ->orderBy('batch_no','ASC')
                                    ->orderBy('box_code','ASC')
                                    ->orderBy('book_no','ASC')
                                    ->when(request()->is_sold && request()->is_sold != 'any', function($q){
                                        $q->where('is_sold', request('is_sold'));
                                    })
                                    ->when(request()->is_activated && request()->is_activated != 'any', function($q){
                                        $q->where('is_activated',request()->is_activated);
                                    })
                                    ->when(request()->game_code && request()->game_code != 'any', function($q){
                                        $q->where('game_code',request()->game_code);
                                    })
                                    ->when(request()->batch_no, function($q){
                                        $q->where('batch_no',request()->batch_no);
                                    })
                                    ->when(request()->box_code, function($q){
                                        $q->where('box_code',request()->box_code);
                                    })
                                    ->when(request()->book_no, function($q){
                                        $q->where('book_no',request()->book_no);
                                    })
                                    ->paginate(100);

        $products = Product::all()->keyBy('game_code');

        return view('product.stock.index',compact('productItems','products'));
    }
}

resources/views/product/add-update.blade.php
@extends('layouts.master')

@section('content')
<!-- Page header -->
<div class="page-header page-header-light">
    <div class="page-header-content header-elements-md-inline">
        <div class="page-title d-flex py-2">
            <h4><span class="font-weight-semibold">{{ isset($product) ? 'Update New Product' : 'Add New Product' }}</span></h4>
        </div>

        <div class="header-elements d-none">
            <div class="d-flex justify-content-center">
                <a href=" {{ route('products.index') }} " class="btn btn-primary btn-sm">
                    <i class="icon-square-left mr-1"></i> Back
                </a>
            </div>
        </div>
    </div>

    <div class="breadcrumb-line breadcrumb-line-light header-elements-md-inline">
        <div class="d-flex">
            <div class="breadcrumb">
                <a href="{{ route('dashboard') }}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> Dashboard</a>
                <span class="breadcrumb-item active">Product</span>
            </div>
        </div>
    </div>
</div>
<!-- /page header -->

<div class="content">
    <div class="card">
        @if(isset($product))
            {{ Form::model($product,['route' => ['products.update',$product->id], 'method' => 'PUT', 'enctype' => 'multipart/form-data']) }}
            @else
            {{ Form::open(['route' => 'products.store', 'method' => 'POST', 'enctype' => 'multipart/form-data']) }}
            @endif
        @csrf
        <div class="card-body">
            <div class="row">
                <div class="col-lg-6">
                    <div class="form-group form-group-float form-group-feedback form-group-feedback-right">
                        <label class="form-group-float-label font-weight-semibold is-visible {{ $errors->has('game_code') ? 'text-danger' : '' }}">Game Code</label>
                        <div class="position-relative">
                            {{
                                Form::text("game_code",isset($product) ? $product->game_code : '',
                                    ["class" => "form-control ".($errors->has('game_code') ? 'border-danger' : ''),"placeholder" => ""])
                            }}
                            @if($errors->has('game_code'))
                                <div class="form-control-feedback text-danger">
                                    <i class="icon-spam"></i>
                                </div>
                            @endif
                        </div>
                        @if($errors->has('game_code'))
                            <span class="form-text text-danger">{{ $errors->first('game_code') }}</span>
                        @endif
                    </div>
                    <div class="form-group form-group-float form-group-feedback form-group-feedback-right">
                        <label class="form-group-float-label font-weight-semibold is-visible {{ $errors->has('name') ? 'text-danger':'' }}">Name</label>
                        <div class="position-relative">
                            {{
                                Form::text("name",isset($product) ? $product->name : '',
                                    ["class" => "form-control ".($errors->has('name') ? 'border-danger' : ''),"placeholder" => ""])
                            }}
                            @if($errors->has('name'))
                                <div class="form-control-feedback text-danger">
                                    <i class="icon-spam"></i>
                                </div>
                            @endif
                        </div>
                        @if($errors->has('name'))
                            <span class="form-text text-danger">{{ $errors->first('name') }}</span>
                        @endif
                    </div>
                    <div class="form-group form-group-float form-group-feedback form-group-feedback-right">
                        <label class="form-group-float-label font-weight-semibold is-visible {{ $errors->has('unit_id')?'text-danger':'' }}">Product unit</label>
                        <div class="position-relative">
                            {{Form::select("unit_id",$units,isset($units) ? $units : null ,["class" => "form-control"])}}
                        </div>
                        @if($errors->has('unit_id'))
                            <div class="form-control-feedback text-danger">
                                <i class="icon-spam"></i>
                            </div>
                        @endif
                    </div>

                    <div class="form-group form-group-float form-group-feedback form-group-feedback-right">
                        <label class="form-group-float-label font-weight-semibold is-visible {{ $errors->has('ticket_qty')?'text-danger':'' }}">Ticket qty in a book</label>
                        <div class="position-relative">
                            {{Form::number("ticket_qty",null,["class" => "form-control ".($errors->has('ticket_qty')?'border-danger':'')])}}
                            @if($errors->has('ticket_qty'))
                                <div class="form-control-feedback text-danger">
                                    <span class="form-text text-danger">{{ $errors->first('ticket_qty') }}</span>
                                </div>
                            @endif
                        </div>
                    </div>
                    <div class="form-group form-group-float form-group-feedback form-group-feedback-right">
                        <label class="form-group-float-label font-weight-semibold is-visible {{ $errors->has('ticket_price')?'text-danger':'' }}">One Ticket Price (R)</label>
                        <div class="position-relative">
                            {{Form::number("ticket_price",null,["class" => "form-control ".($errors->has('ticket_price')?'border-danger':'')])}}
                            @if($errors->has('ticket_price'))
                                <div class="form-control-feedback text-danger">
                                    <span class="form-text text-danger">{{ $errors->first('ticket_price') }}</span>
                                </div>
                            @endif
                        </div>
                    </div>
                </div>
            </div>
        </div>

        @can('product-modification')
        <div class="card-footer">
            <button type="submit" class="btn btn-success">
                <i class="icon-folder mr-1"></i> {{ isset($product) ? 'Update' : 'Save'}}
            </button>
        </div>
        @endcan

        {{ Form::close() }}
    </div>
</div>
@endsection

resources/views/product/index.blade.php
@extends('layouts.master')

@section('content')
<!-- Page header -->
<div class="page-header page-header-light">
    <div class="page-header-content header-elements-md-inline">
        <div class="page-title d-flex py-2">
            <h4><span class="font-weight-semibold">Products</span></h4>
        </div>
        <div class="header-elements d-none">
            <div class="d-flex justify-content-center">
                @can('view-stock')
                <a href="{{ route('product.stock.index') }}" class="btn btn-success btn-sm mr-2">
                    <i class="icon-home7 text-white"></i> View Stock
                </a>
                @endcan

                @can('add-new-stock')
                <a href="{{ route('stocks.index') }}" class="btn btn-success btn-sm mr-2">
                    <i class="icon-home7 text-white"></i> Stock In
                </a>
                @endcan

                @can('add-new-product')
                <a href="{{ route('products.create') }}" class="btn btn-primary btn-sm">
                    <i class="icon-stack-picture text-white"></i> Add New Product
                </a>
                @endcan
            </div>
        </div>
    </div>

    <div class="breadcrumb-line breadcrumb-line-light header-elements-md-inline">
        <div class="d-flex">
            <div class="breadcrumb">
                <a href="{{route('dashboard')}}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> Dashboard</a>
                <span class="breadcrumb-item active">Product</span>
            </div>
        </div>
    </div>
</div>
<!-- /page header -->

<div class="content">
    <div class="card">
        <div class="card-header">
            @include('includes.success-msg')
            @include('includes.error-msg')
            <div class="mb-1">
                <button class="btn btn-sm btn-primary" type="button" data-toggle="collapse" data-target="#filter" aria-expanded="false" aria-controls="collapseExample">
                    <i class="icon-filter3"> </i> Filter
                </button>

                <div class="collapse mt-2" id="filter">
                    {{ Form::open(['route' => 'products.index', 'method' => 'GET']) }}
                        <div class="row mb-2">
                            <div class="col-lg-3 col-md-4 col-sm-6">
                                <label for="">Game Code</label>
                                {{Form::text("game_code",request()->game_code,["class" => "form-control "])}}
                            </div>
                            <div class="col-lg-3 col-md-4 col-sm-6">
                                <label for="">Batch No</label>
                                {{Form::text("batch_no",request()->batch_no,["class" => "form-control "])}}
                            </div>
                        </div>
                        <button type="submit" class="btn btn-sm btn-success">Search</button>
                        <a href="{{route('products.index')}}" class="btn btn-sm btn-danger">Reset</a>
                    {{ Form::close() }}
                </div>
            </div>
            <div class="table-responsive">
                <table class="table table-bordered">
                    <thead>
                        <tr class="bg-slate-800">
                            <th>#</th>
                            <th>Game Code</th>
                            <th>In Stock</th>
                            <th>Tickets Per Book</th>
                            <th>Total Tickets</th>
                            <th>One Ticket Price (R)</th>
                            <th>Estimate Total Price ($)</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if(isset($products) && $products->count() > 0)
                            @foreach($products as $key => $row)
                            <tr>
                                <td>{{($products->perPage() * ($products->currentPage() - 1)) + $key + 1}}</td>
                                <td width="200px">{{ $row->game_code }} – {{ $row->name }}</td>
                                <td><a href="{{route('product.stock.index')}}?game_code= {{ $row->game_code }}"  class="text-primary"> {{ $row->product_items ? $row->available_product_items->count() : 0 }} </a>  {{ $row->product_unit ? $row->product_unit->name : ''}}</td>
                                <td >{{ currencyFormat($row->ticket_qty,0) }}</td>
                                <td >{{ currencyFormat($row->ticket_qty * $row->available_product_items->count(),0) }}</td>
                                <td>R {{ $row->ticket_price ? currencyFormat($row->ticket_price) : 0 }}</td>
                                <td>R {{ $row->available_product_items ? currencyFormat($row->available_product_items->count() * $row->ticket_qty * $row->ticket_price) : 0.00 }}</td>
                                <td width="300px" class="group-btn-action">
                                    <div class="btn-group">
                                        @can('view-stock')
                                            <a href="{{route('product.stock.index')  }}?game_code= {{ $row->game_code }}" class="btn btn-sm btn-outline bg-success border-success text-success-800 btn-icon border-2"><i class="icon-home7"></i> View Stock</a>
                                        @endcan

                                        <a href="{{route('products.edit',$row->id)  }}" class="btn btn-sm btn-outline bg-primary border-primary text-primary-800 btn-icon border-2 ml-1"><i class="icon-pencil7"></i> Edit</a>

                                        @can('product-modification')
                                            <button type="button" class="btn btn-sm btn-outline bg-danger border-danger text-danger-800 btn-icon border-2 delete ml-1" data-route="{{route('products.destroy',$row->id)}}"><i class="icon-trash"></i> Delete</button>
                                        @endcan
                                    </div>
                                </td>
                            </tr>
                            @endforeach
                        @else
                            <tr>
                                <td colspan="8"> No data</td>
                            </tr>
                        @endif
                    </tbody>
                </table>
            </div>
            @if(isset($products) && count($products) > 0)
            <div class="card-footer">
                @if($products->hasPages())
                    <div class="mb-2">
                        {!! $products->appends(Input::except('page'))->render() !!}
                    </div>
                @endif
                <div>
                    Showing {{$products->firstItem()}} to {{$products->lastItem()}}
                    of  {{$products->total()}} entries
                </div>
            </div>
            @endif
        </div>
    </div>
</div>
@endsection

@section('page-script')
<script src="/global_assets/js/demo_pages/form_inputs.js"></script>
<script src="/global_assets/js/plugins/forms/styling/uniform.min.js"></script>
<script src="/global_assets/js/plugins/ui/moment/moment.min.js"></script>
@endsection